/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConversationId = IDL.Nat;
export const MessageRole = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : MessageRole,
  'timestamp' : Timestamp,
});
export const Conversation = IDL.Record({
  'id' : ConversationId,
  'title' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'owner' : IDL.Principal,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
});
export const ConversationSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'messageCount' : IDL.Nat,
});
export const SendMessageResult = IDL.Variant({
  'ok' : Message,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
  'freeTierLimitReached' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func([], [ConversationId], []),
  'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
  'getAnonymousMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(Conversation)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [SendMessageResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateConversationTitle' : IDL.Func(
      [ConversationId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConversationId = IDL.Nat;
  const MessageRole = IDL.Variant({
    'user' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : MessageRole,
    'timestamp' : Timestamp,
  });
  const Conversation = IDL.Record({
    'id' : ConversationId,
    'title' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'owner' : IDL.Principal,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
  });
  const ConversationSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'messageCount' : IDL.Nat,
  });
  const SendMessageResult = IDL.Variant({
    'ok' : Message,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
    'freeTierLimitReached' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func([], [ConversationId], []),
    'deleteConversation' : IDL.Func([ConversationId], [IDL.Bool], []),
    'getAnonymousMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(Conversation)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'sendMessage' : IDL.Func(
        [ConversationId, IDL.Text],
        [SendMessageResult],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateConversationTitle' : IDL.Func(
        [ConversationId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };